import { ArrowRight, CalendarDays, MapPin, Search, Sparkles, SunMedium, WalletCards } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { getErrorMessage } from '../api/client';
import { destinationApi } from '../api/tripService';
import Card from '../components/Card';
import LoadingSpinner from '../components/LoadingSpinner';

const photos = {
  Bali: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=85', Kyoto: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=85', Lisbon: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1200&q=85', Reykjavik: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=85', Singapore: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=85', 'New York': 'https://images.unsplash.com/photo-1496588152823-86ff7695e68f?auto=format&fit=crop&w=1200&q=85', 'Cape Town': 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1200&q=85', Dubai: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=85', Paris: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=85', Rome: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1200&q=85', Sydney: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=85', Bangkok: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=1200&q=85', Marrakech: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=85', Vancouver: 'https://images.unsplash.com/photo-1559511260-66a654ae982a?auto=format&fit=crop&w=1200&q=85'
};

export default function Destinations() {
  const [destinations, setDestinations] = useState(null); const [query, setQuery] = useState(''); const [region, setRegion] = useState('All'); const [error, setError] = useState('');
  useEffect(() => { destinationApi.list().then(setDestinations).catch((err) => setError(getErrorMessage(err))); }, []);
  const regions = useMemo(() => ['All', ...new Set((destinations || []).map((d) => d.region))], [destinations]);
  const filtered = useMemo(() => (destinations || []).filter((d) => { const needle = query.trim().toLowerCase(); return (region === 'All' || d.region === region) && (!needle || [d.name, d.country, d.summary].some((value) => value?.toLowerCase().includes(needle))); }), [destinations, query, region]);
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-10 text-white shadow-soft md:px-8"><img src="https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1800&q=85" alt="Travel landscape" className="absolute inset-0 h-full w-full object-cover opacity-55" /><div className="absolute inset-0 bg-slate-950/65" /><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-black/25 px-3 py-1 text-xs font-semibold uppercase tracking-[.18em]"><Sparkles className="h-3.5 w-3.5" />Curated discovery</span><h1 className="mt-5 text-3xl font-bold tracking-tight md:text-5xl">Find the feeling you want to travel for.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-200 md:text-base">Choose a place that fits your pace, then move it straight into a ready-to-plan trip.</p></div></section>
    <section className="rounded-3xl border border-white/70 bg-white/80 p-4 shadow-soft"><div className="grid gap-3 md:grid-cols-[1fr_180px]"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search a city or travel style" className="w-full rounded-2xl border border-slate-200 bg-white py-3 pl-10 pr-4 text-sm outline-none focus:border-blue-500" /></label><select value={region} onChange={(e) => setRegion(e.target.value)} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 outline-none focus:border-blue-500">{regions.map((item) => <option key={item}>{item}</option>)}</select></div></section>
    {error && <Card><p className="text-sm text-red-600">{error}</p></Card>}
    {!destinations ? <LoadingSpinner label="Loading destinations" /> : <div className="grid items-stretch gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((d) => <article key={d.id} className="group grid overflow-hidden rounded-[1.75rem] border border-white/70 bg-white shadow-soft transition hover:-translate-y-1 hover:shadow-xl" style={{ height: '600px', gridTemplateRows: '224px minmax(0, 1fr)' }}><div className="relative overflow-hidden bg-slate-900 p-5 text-white"><img src={photos[d.name] || photos.Bali} alt={`${d.name}, ${d.country}`} className="absolute inset-0 z-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 z-[1] bg-slate-950/45" /><div className="relative z-10 flex justify-between"><span className="inline-flex items-center gap-1 rounded-full bg-black/35 px-2.5 py-1 text-xs font-semibold backdrop-blur"><MapPin className="h-3.5 w-3.5" />{d.region}</span><span className="text-sm font-medium">{d.country}</span></div><h2 className="absolute bottom-5 left-5 z-10 text-3xl font-bold tracking-tight">{d.name}</h2></div><div className="grid min-h-0 gap-2.5 p-5" style={{ gridTemplateRows: '60px 76px 28px minmax(0, 1fr) 44px' }}><p className="overflow-hidden text-sm leading-6 text-slate-600">{d.summary}</p><div className="grid grid-cols-2 gap-2 text-xs"><div className="rounded-2xl bg-slate-50 p-3"><CalendarDays className="mb-2 h-4 w-4 text-blue-600" /><p className="font-semibold text-slate-900">{d.recommendedDays}</p><p className="mt-0.5 text-slate-500">Ideal length</p></div><div className="rounded-2xl bg-slate-50 p-3"><WalletCards className="mb-2 h-4 w-4 text-emerald-600" /><p className="font-semibold text-slate-900">{d.budgetRange}</p><p className="mt-0.5 text-slate-500">Est. budget</p></div></div><p className="flex items-center gap-2 overflow-hidden whitespace-nowrap text-xs text-slate-500"><SunMedium className="h-4 w-4 shrink-0 text-amber-500" />Best: {d.bestTime}</p><div className="min-h-0 overflow-hidden border-t border-slate-100 pt-2"><p className="mb-1.5 text-xs font-bold uppercase tracking-[.12em] text-slate-500">Top places to explore</p><div className="flex flex-nowrap gap-1.5 overflow-hidden">{d.attractions.slice(0, 3).map((place) => <span key={place} className="shrink-0 rounded-full bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700">{place}</span>)}</div></div><Link className="flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white transition hover:bg-slate-700" to={`/trips/new?title=${encodeURIComponent(`${d.name} escape`)}&destination=${encodeURIComponent(`${d.name}, ${d.country}`)}`}>Plan this trip <ArrowRight className="h-4 w-4" /></Link></div></article>)}{filtered.length === 0 && <Card className="md:col-span-2 xl:col-span-3"><p className="text-sm text-slate-500">No destinations match those filters.</p></Card>}</div>}
  </div>;
}
