spring.application.name=tripnest-backend

server.port=8080


# ---------- Database ----------
spring.datasource.url=jdbc:postgresql://localhost:5432/tripnest
spring.datasource.username=postgres
spring.datasource.password=DB_Password
spring.datasource.driver-class-name=org.postgresql.Driver


# ---------- JPA ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ---------- JWT ----------
jwt.secret=YOUR_JWT_SECRET_KEY
jwt.expiration-ms=86400000


# ---------- Mail ----------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# ---------- Google OAuth2 ----------
spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile